#!/usr/bin/env bun
import { existsSync, readFileSync, writeFileSync, chmodSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';

// Implementations live in packages/swarm/src/executor/bridges. Legacy entry
// points contain only these generated forwarders, never their own CLI policy.
export const bridgeShimTargets = [
  ...['claude-code', 'codex', 'gemini', 'hermes', 'kimi', 'opencode', 'pi'].map(id => ({
    path: `Skills/zo-swarm-executors/bridges/${id}-bridge.sh`,
    id,
    submodule: 'Skills/zo-swarm-executors',
  })),
  { path: 'Skills/zo-swarm-orchestrator/scripts/claude-code-bridge.sh', id: 'claude-code', submodule: 'Skills/zo-swarm-orchestrator' },
  { path: 'packages/swarm/scripts/claude-code-bridge.sh', id: 'claude-code', submodule: null },
] as const;

export function renderBridgeShim(target: typeof bridgeShimTargets[number]): string {
  const rootRelative = relative(dirname(target.path), '.') || '.';
  return `#!/usr/bin/env bash
# Generated by packages/swarm/scripts/sync-bridge-shims.ts; edit the canonical bridge.
set -euo pipefail
SCRIPT_DIR="$(cd -- "$(dirname -- "\${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="\${ZOUROBOROS_WORKSPACE_ROOT:-$(cd -- "$SCRIPT_DIR/${rootRelative}" && pwd)}"
BRIDGE="$WORKSPACE_ROOT/packages/swarm/src/executor/bridges/${target.id}-bridge.sh"
if [[ ! -f "$BRIDGE" ]]; then
  echo "BRIDGE_ERROR: canonical ${target.id} bridge missing; use the complete workspace or set ZOUROBOROS_WORKSPACE_ROOT" >&2
  exit 127
fi
exec bash "$BRIDGE" "$@"
`;
}

export function syncBridgeShims(root: string, write = false, requireSubmodules = false): string[] {
  const failures: string[] = [];
  for (const target of bridgeShimTargets) {
    if (target.submodule && !existsSync(join(root, target.submodule, '.git'))) {
      if (requireSubmodules) failures.push(`Uninitialized submodule: ${target.submodule}`);
      continue;
    }
    const path = join(root, target.path);
    const expected = renderBridgeShim(target);
    if (write) {
      writeFileSync(path, expected);
      chmodSync(path, 0o755);
    } else if (!existsSync(path) || readFileSync(path, 'utf8') !== expected) {
      failures.push(`Bridge shim drift: ${target.path}`);
    }
  }
  return failures;
}

if (import.meta.main) {
  const failures = syncBridgeShims(
    resolve(import.meta.dir, '../../..'),
    process.argv.includes('--write'),
    process.argv.includes('--require-submodules'),
  );
  if (failures.length) {
    console.error(failures.join('\n'));
    process.exitCode = 1;
  }
}
