#!/usr/bin/env bun
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

export const runtimeCopies = [
  ...['packages/swarm/src/standalone', 'Skills/zouroboros/skills/swarm/scripts'].flatMap(directory => [
    { path: `${directory}/orchestrate-v5.ts`, target: 'orchestrate-v5.ts' },
    { path: `${directory}/orchestrate-v5-backup.ts`, target: 'orchestrate-v5.ts' },
  ]),
  ...['mcp-server.ts', 'mcp-server-http.ts', 'swarm-hybrid-runner.ts'].map(target => ({
    path: `packages/swarm/src/standalone/${target}`, target,
  })),
];
export const executorToolCopies = ['doctor', 'register', 'test-harness'].map(name => ({
  path: `Skills/zo-swarm-executors/scripts/${name}.ts`,
  target: `packages/swarm/src/executor/${name}.ts`,
}));
export const orchestratorCopies = [
  'orchestrate-v5.ts', 'orchestrate-v5-backup.ts', 'mcp-server.ts', 'mcp-server-http.ts', 'swarm-hybrid-runner.ts',
].map(name => ({
  path: `Skills/zo-swarm-orchestrator/scripts/${name}`,
  target: name === 'orchestrate-v5-backup.ts' ? 'orchestrate-v5.ts' : name,
}));
export const canonicalRegistry = 'packages/swarm/src/executor/registry/executor-registry.json';
export const generatedRegistry = 'Skills/zo-swarm-executors/registry/executor-registry.json';

// Self-contained so export-skills.sh can copy these entry points into Skills.
// Resolve code beside this entry point first; workspace env vars can point at
// separate runtime data. An exported copy outside the repo needs the override.
export function renderRuntimeForwarder(target: string): string {
  const canonicalPath = target.startsWith('packages/') ? target : `packages/swarm/scripts/${target}`;
  return `#!/usr/bin/env bun
// Generated by packages/swarm/scripts/sync-runtime-copies.ts; edit ${canonicalPath}.
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const roots: string[] = [];
for (let root = dirname(fileURLToPath(import.meta.url)); ; root = dirname(root)) {
  roots.push(root);
  if (dirname(root) === root) break;
}
if (process.env.ZOUROBOROS_WORKSPACE_ROOT) roots.push(process.env.ZOUROBOROS_WORKSPACE_ROOT);
const target = roots.map(root => join(root, '${canonicalPath}'))
  .find(path => existsSync(path) && pathToFileURL(path).href !== import.meta.url);
if (!target) throw new Error('Canonical swarm runtime missing: use the complete workspace or set ZOUROBOROS_WORKSPACE_ROOT');
await import(pathToFileURL(target).href);
`;
}

export function syncRuntimeCopies(root: string, write = false, requireSubmodules = false): string[] {
  const failures: string[] = [];
  const copies = runtimeCopies.map(copy => ({ ...copy, content: renderRuntimeForwarder(copy.target) }));
  const initialized = existsSync(join(root, 'Skills/zo-swarm-executors/.git'));
  if (initialized) {
    copies.push(...executorToolCopies.map(copy => ({ ...copy, content: renderRuntimeForwarder(copy.target) })));
    copies.push({ path: generatedRegistry, target: canonicalRegistry,
      content: readFileSync(join(root, canonicalRegistry), 'utf8') });
  }
  else if (requireSubmodules) failures.push('Uninitialized submodule: Skills/zo-swarm-executors');
  if (existsSync(join(root, 'Skills/zo-swarm-orchestrator/.git'))) {
    copies.push(...orchestratorCopies.map(copy => ({ ...copy, content: renderRuntimeForwarder(copy.target) })));
  } else if (requireSubmodules) failures.push('Uninitialized submodule: Skills/zo-swarm-orchestrator');
  for (const copy of copies) {
    const path = join(root, copy.path);
    if (write) {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, copy.content);
    }
    else if (!existsSync(path) || readFileSync(path, 'utf8') !== copy.content) {
      failures.push(`Runtime copy drift: ${copy.path}`);
    }
  }
  return failures;
}

if (import.meta.main) {
  const failures = syncRuntimeCopies(
    resolve(import.meta.dir, '../../..'), process.argv.includes('--write'),
    process.argv.includes('--require-submodules'),
  );
  if (failures.length) {
    console.error(failures.join('\n'));
    process.exitCode = 1;
  }
}
